"use client";

import React, { useState, useEffect } from "react";
import { useExtractorStore } from "../store/useExtractorStore";
import { OopRulesEngine } from "../lib/oopRulesEngine";
import { Play, Settings, RefreshCw, Layers, CheckCircle2, XCircle, Terminal, HelpCircle, TrendingUp } from "lucide-react";

export default function OopRequestSimulator() {
  const isLoaded = useExtractorStore((state) => state.isLoaded);
  const isOopModel = useExtractorStore((state) => state.isOopModel);
  const oopRules = useExtractorStore((state) => state.oopRules);
  const oopRequestContextString = useExtractorStore((state) => state.oopRequestContextString);
  const oopTrace = useExtractorStore((state) => state.oopTrace);
  const oopFinalContext = useExtractorStore((state) => state.oopFinalContext);
  const updateOopRequest = useExtractorStore((state) => state.updateOopRequest);

  const [jsonText, setJsonText] = useState("");
  const [errorMsg, setErrorMsg] = useState("");
  const [hoveredPoint, setHoveredPoint] = useState<{ x: number; y: number } | null>(null);

  // Populate local state when context string is ready
  useEffect(() => {
    if (oopRequestContextString) {
      setJsonText(oopRequestContextString);
    }
  }, [oopRequestContextString]);

  if (!isLoaded || !isOopModel) return null;

  const handleJsonChange = (val: string) => {
    setJsonText(val);
    try {
      JSON.parse(val);
      setErrorMsg("");
    } catch (e: any) {
      setErrorMsg("Invalid JSON: " + e.message);
    }
  };

  const handleRunSimulation = () => {
    try {
      JSON.parse(jsonText);
      updateOopRequest(jsonText);
      setErrorMsg("");
    } catch (e: any) {
      setErrorMsg("Cannot run. Fix JSON syntax first: " + e.message);
    }
  };

  // Generate sensitivity sweep data points: ProtectionClass (1 to 10) vs BasicPremium
  const getSweepData = () => {
    try {
      const parsedReq = JSON.parse(jsonText || oopRequestContextString || "{}");
      const engine = new OopRulesEngine(oopRules);
      const points: { x: number; y: number }[] = [];

      for (let pc = 1; pc <= 10; pc++) {
        const tempReq = {
          ...parsedReq,
          ProtectionClass: String(pc),
        };
        const { finalContext } = engine.run(tempReq);
        const premium = finalContext["BasicPremium"] ?? finalContext["BaseRate"] ?? 0;
        points.push({ x: pc, y: Number(premium) || 0 });
      }
      return points;
    } catch (e) {
      console.error(e);
      return [];
    }
  };

  const sweepPoints = getSweepData();

  // SVG Chart Layout Math
  const svgWidth = 500;
  const svgHeight = 220;
  const padding = 45;
  const plotWidth = svgWidth - 2 * padding;
  const plotHeight = svgHeight - 2 * padding;

  const yValues = sweepPoints.map((p) => p.y);
  const yMin = Math.max(0, Math.min(...yValues) * 0.9);
  const yMax = Math.max(...yValues) * 1.1 || 100;

  const getSvgCoords = (x: number, y: number) => {
    const xRange = 9; // 10 - 1
    const yRange = yMax - yMin;
    
    const svgX = padding + ((x - 1) / xRange) * plotWidth;
    const svgY = padding + plotHeight - ((y - yMin) / yRange) * plotHeight;
    return { x: svgX, y: svgY };
  };

  // Build line path definition
  let pathD = "";
  let areaD = "";
  if (sweepPoints.length > 0) {
    const startCoord = getSvgCoords(sweepPoints[0].x, sweepPoints[0].y);
    pathD = `M ${startCoord.x} ${startCoord.y}`;
    areaD = `M ${startCoord.x} ${padding + plotHeight} L ${startCoord.x} ${startCoord.y}`;

    for (let i = 1; i < sweepPoints.length; i++) {
      const coord = getSvgCoords(sweepPoints[i].x, sweepPoints[i].y);
      pathD += ` L ${coord.x} ${coord.y}`;
      areaD += ` L ${coord.x} ${coord.y}`;
    }

    const endCoord = getSvgCoords(sweepPoints[sweepPoints.length - 1].x, sweepPoints[sweepPoints.length - 1].y);
    areaD += ` L ${endCoord.x} ${padding + plotHeight} Z`;
  }

  // Extract variables generated by the rules (not in the original request)
  const originalKeys = Object.keys(JSON.parse(oopRequestContextString || "{}"));
  const calculatedVars = Object.keys(oopFinalContext)
    .filter((k) => !originalKeys.includes(k) && k !== "PolicyYear" && k !== "EffDate")
    .map((key) => ({
      key,
      value: oopFinalContext[key],
    }));

  return (
    <div className="space-y-6">
      
      {/* Description Panel */}
      <div className="bg-white border border-gray-200 p-5 rounded-3xl shadow-sm flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h3 className="text-sm font-bold text-gray-800 flex items-center gap-2">
            <Settings className="h-5 w-5 text-emerald-500" /> OOP Rating Engine Simulator
          </h3>
          <p className="text-[11px] text-gray-400 mt-0.5 font-medium">
            Execute parsed row-based business logic components step-by-step against mock transaction requests.
          </p>
        </div>
        <button
          onClick={handleRunSimulation}
          className="flex items-center gap-1.5 px-4 py-2 bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl text-xs font-bold transition-all shadow-xs"
        >
          <Play className="h-4 w-4 fill-current" /> Run Rating Simulation
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        
        {/* Left Column: JSON Request Editor */}
        <div className="bg-white border border-gray-200 rounded-3xl p-5 shadow-sm space-y-4">
          <div className="border-b border-gray-100 pb-3 flex justify-between items-center">
            <h4 className="text-xs font-extrabold text-gray-400 uppercase tracking-wider flex items-center gap-1.5">
              <Terminal className="h-4 w-4 text-emerald-500" /> Input Transaction Request
            </h4>
          </div>

          <div className="space-y-2">
            <textarea
              value={jsonText}
              onChange={(e) => handleJsonChange(e.target.value)}
              className="w-full h-[380px] p-3.5 bg-gray-900 text-emerald-400 font-mono text-xs rounded-2xl border border-zinc-800 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 leading-relaxed shadow-inner"
            />
            {errorMsg ? (
              <p className="text-[10px] text-rose-500 font-bold bg-rose-50 p-2.5 rounded-xl border border-rose-100">
                {errorMsg}
              </p>
            ) : (
              <p className="text-[9px] text-gray-400">
                Modify transaction fields (e.g. ProtectionClass, Deductible) and run to see outcome changes.
              </p>
            )}
          </div>
        </div>

        {/* Middle Column: Step Trace execution list */}
        <div className="lg:col-span-2 bg-white border border-gray-200 rounded-3xl shadow-sm overflow-hidden flex flex-col">
          <div className="border-b border-gray-200 px-5 py-4 bg-gray-50/50 flex justify-between items-center">
            <h3 className="text-xs font-extrabold text-gray-400 uppercase tracking-wider flex items-center gap-2">
              <Layers className="h-4 w-4 text-emerald-500" /> OOP Rating Steps Trace
            </h3>
            <span className="text-[10px] text-emerald-600 font-bold bg-emerald-50 px-2 py-0.5 rounded border border-emerald-100">
              {oopTrace.length} Steps Executed
            </span>
          </div>

          <div className="p-5 overflow-y-auto max-h-[440px] space-y-3">
            {oopTrace.map((step, idx) => (
              <div
                key={idx}
                className={`p-3.5 border rounded-2xl flex items-start justify-between gap-4 transition-all ${
                  step.met
                    ? "bg-emerald-50/20 border-emerald-100"
                    : "bg-gray-50/40 border-gray-100 opacity-60"
                }`}
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[9px] font-bold bg-gray-100 text-gray-500 px-1.5 py-0.2 rounded border border-gray-200 font-mono">
                      Order {step.order}
                    </span>
                    <span className="text-[10px] font-extrabold text-gray-700 font-mono">ID {step.id}</span>
                  </div>
                  <p className="text-xs font-bold text-gray-800">{step.desc}</p>
                  <p className="text-[10px] text-emerald-600 font-mono font-medium">{step.action}</p>
                </div>

                <div className="shrink-0 mt-0.5">
                  {step.met ? (
                    <span className="flex items-center gap-1 text-[10px] font-bold text-emerald-600">
                      <CheckCircle2 className="h-4 w-4" /> MET
                    </span>
                  ) : (
                    <span className="flex items-center gap-1 text-[10px] font-bold text-gray-400">
                      <XCircle className="h-4 w-4" /> SKIPPED
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Calculated Rating Outcomes Grid & SVG Sensitivity Chart */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Output Variables Grid (2/3 width) */}
        <div className="lg:col-span-2 bg-white border border-gray-200 rounded-3xl p-5 shadow-sm space-y-4">
          <h4 className="text-xs font-extrabold text-gray-400 uppercase tracking-wider flex items-center gap-2 border-b border-gray-100 pb-3">
            <HelpCircle className="h-5 w-5 text-emerald-500" /> Resolved Rating Output Variables
          </h4>
          
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {calculatedVars.length > 0 ? (
              calculatedVars.map((v) => (
                <div key={v.key} className="p-3 bg-gray-50 border border-gray-100 rounded-2xl flex flex-col justify-between">
                  <span className="text-[10px] font-bold font-mono text-gray-500 block truncate">{v.key}</span>
                  <span className="text-sm font-extrabold font-mono text-emerald-600 block mt-1.5">
                    {typeof v.value === "number" ? v.value.toLocaleString(undefined, { maximumFractionDigits: 3 }) : String(v.value)}
                  </span>
                </div>
              ))
            ) : (
              <p className="text-xs text-gray-400 col-span-full">No rating variables computed yet.</p>
            )}
          </div>
        </div>

        {/* SVG Sensitivity Line Chart (1/3 width) */}
        <div className="bg-white border border-gray-200 rounded-3xl p-5 shadow-sm space-y-4">
          <div className="flex justify-between items-center border-b border-gray-100 pb-3">
            <h4 className="text-xs font-extrabold text-gray-400 uppercase tracking-wider flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-emerald-500" /> Sensitivity Graph
            </h4>
            <span className="text-[9px] text-gray-400 font-bold uppercase">Class vs Premium</span>
          </div>

          <div className="relative flex justify-center">
            {sweepPoints.length > 0 ? (
              <svg width={svgWidth} height={svgHeight} viewBox={`0 0 ${svgWidth} ${svgHeight}`} className="w-full h-auto overflow-visible select-none">
                <defs>
                  <linearGradient id="chartGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#10b981" stopOpacity="0.25" />
                    <stop offset="100%" stopColor="#10b981" stopOpacity="0.0" />
                  </linearGradient>
                </defs>

                {/* Grid Lines */}
                {Array.from({ length: 5 }).map((_, idx) => {
                  const yVal = yMin + (idx / 4) * (yMax - yMin);
                  const coord = getSvgCoords(1, yVal);
                  return (
                    <g key={idx}>
                      <line
                        x1={padding}
                        y1={coord.y}
                        x2={padding + plotWidth}
                        y2={coord.y}
                        stroke="#e5e7eb"
                        strokeWidth="1"
                        strokeDasharray="4 4"
                      />
                      <text
                        x={padding - 8}
                        y={coord.y + 3}
                        textAnchor="end"
                        className="font-sans text-[8px] fill-gray-400 font-bold"
                      >
                        ${Math.round(yVal)}
                      </text>
                    </g>
                  );
                })}

                {/* X Axis Coordinates */}
                {[1, 4, 7, 10].map((xVal) => {
                  const coord = getSvgCoords(xVal, yMin);
                  return (
                    <g key={xVal}>
                      <line
                        x1={coord.x}
                        y1={padding + plotHeight}
                        x2={coord.x}
                        y2={padding + plotHeight + 4}
                        stroke="#d1d5db"
                        strokeWidth="1"
                      />
                      <text
                        x={coord.x}
                        y={padding + plotHeight + 12}
                        textAnchor="middle"
                        className="font-sans text-[8px] fill-gray-400 font-bold"
                      >
                        PC {xVal}
                      </text>
                    </g>
                  );
                })}

                {/* Area Fill */}
                <path d={areaD} fill="url(#chartGrad)" />

                {/* Line Path */}
                <path d={pathD} fill="none" stroke="#10b981" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />

                {/* Points */}
                {sweepPoints.map((p, idx) => {
                  const coord = getSvgCoords(p.x, p.y);
                  const isHovered = hoveredPoint?.x === p.x;
                  return (
                    <circle
                      key={idx}
                      cx={coord.x}
                      cy={coord.y}
                      r={isHovered ? 6 : 4}
                      fill={isHovered ? "#059669" : "#10b981"}
                      stroke="#ffffff"
                      strokeWidth="1.5"
                      className="cursor-pointer transition-all"
                      onMouseEnter={() => setHoveredPoint(p)}
                      onMouseLeave={() => setHoveredPoint(null)}
                    />
                  );
                })}

                {/* Tooltip text inside SVG */}
                {hoveredPoint && (
                  <g>
                    <rect
                      x={getSvgCoords(hoveredPoint.x, hoveredPoint.y).x - 45}
                      y={getSvgCoords(hoveredPoint.x, hoveredPoint.y).y - 28}
                      width="90"
                      height="20"
                      rx="6"
                      fill="#1f2937"
                    />
                    <text
                      x={getSvgCoords(hoveredPoint.x, hoveredPoint.y).x}
                      y={getSvgCoords(hoveredPoint.x, hoveredPoint.y).y - 15}
                      textAnchor="middle"
                      fill="#ffffff"
                      className="font-mono text-[9px] font-bold"
                    >
                      PC {hoveredPoint.x}: ${Math.round(hoveredPoint.y)}
                    </text>
                  </g>
                )}
              </svg>
            ) : (
              <p className="text-xs text-gray-400">Sweep points not available.</p>
            )}
          </div>
          
          <p className="text-[9px] text-gray-400 font-medium text-center leading-normal">
            This live chart sweeps the Protection Class (PC 1-10) against your input to plot base rating premium outcomes dynamically.
          </p>
        </div>

      </div>

    </div>
  );
}
